ACTIVAD CLASE 2- Datos de Prueba:

1. Tienes un archivo llamado "ventas.csv" que contiene información sobre las ventas de productos. Cada fila representa una venta y contiene varias columnas con los datos sobre las ventas.
 2. Tienes un archivo llamado "clientes.json" con datos de los clientes que realizaron las compras. Cada objeto JSON representa un cliente y contiene sus datos.
3. Existe un archivo llamado "inventario.xlsx" con información sobre el inventario de productos. La hoja de cálculo contiene varias columnas con datos sobre los productos.   

Tu tarea es utilizar la librería PANDAS para importar estos datos desde los diferentes formatos (CSV, JSON y Excel), combinarlos en una estructura de datos adecuada y realizar las siguientes acciones:

1 a. Cargar los datos de ventas desde el archivo CSV(se agrego datos al dataset)

In [4]:
import pandas as pd
dat_csv = pd.read_csv('archivos semana 2/ventas.csv', encoding='ISO-8859-1')#NOTA: El archivo 'ventas.csv' esta en la carpeta 'archivos semana 2'. 
dat_csv

   id_venta       fecha  producto  cantidad  precio_unitario
0         1  2026-01-10  Notebook         2             1200
1         2  2026-01-12     Mouse         5               25
2         3  2026-01-15   Teclado         3               45
3         4  2026-01-18   Monitor         1              300
4         5  2026-01-19  Auxiliar         3              200
5         6  2026-01-20   Monitor         2              300
6         7  2026-01-21  Auxiliar         1              200
7         8  2026-01-22  Notebook         3             1200
8         9  2026-01-23   Teclado         2               45
9        10  2026-01-24     Mouse         3               25

1 b. Mostrar una vista previa de las primeras filas

In [5]:
dat_csv.head() #Se agrego datos pero muestra las primeras filas del DataFrame.

   id_venta       fecha  producto  cantidad  precio_unitario
0         1  2026-01-10  Notebook         2             1200
1         2  2026-01-12     Mouse         5               25
2         3  2026-01-15   Teclado         3               45
3         4  2026-01-18   Monitor         1              300
4         5  2026-01-19  Auxiliar         3              200

2. Cargar los datos de clientes desde el archivo JSON y mostrar la cantidad total de clientes.

In [ ]:
import pandas as pd
#Se mantiene la ruta de la carpeta
dat_json = pd.read_json('archivos semana 2/clientes.json', encoding='ISO-8859-1')


#Cantidad total de clientes con función shape[0] nos da el número de registros
total_clientes = dat_json.shape[0]

print(f"La cantidad total de clientes es: {total_clientes}")
print(dat_json)

La cantidad total de clientes es: 3
   id_cliente         nombre             email   telefono
0           1    Juan PÃ©rez    juan@email.com  123456789
1           2  MarÃ­a LÃ³pez   maria@email.com  987654321
2           3  Carlos GÃ³mez  carlos@email.com  456123789

3. a- Cargar los datos de inventario desde la hoja de cálculo Excel.

In [17]:
#codigo para leer el archivo excel
!python -m pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [18]:
import pandas as pd
#NOTA archivo 'inventario.xlsx' esta en la carpeta 'archivos semana 2'
dat_excel = pd.read_excel('archivos semana 2/inventario.xlsx')
dat_excel

   id_producto    nombre    categoria  stock  precio
0            1  Notebook  Electrónica     10    1200
1            2     Mouse   Accesorios     50      25
2            3   Teclado   Accesorios     30      45
3            4   Monitor  Electrónica     15     300

3. b- Calcular el promedio de stock disponible para todos los productos.

In [ ]:
promedio_stock = dat_excel['stock'].mean()
print(f"El promedio de stock disponible es: {promedio_stock}")

# Se calcula el valor total del inventario (Precio * Stock de cada producto)
valor_total_inventario = (dat_excel['precio'] * dat_excel['stock']).sum()

# Calculamos la cantidad total de unidades en stock
unidades_totales = dat_excel['stock'].sum()

# Por ultimo el promedio del precio ponderado por el stock
promedio_precio_stock = valor_total_inventario / unidades_totales

print(f"Suma total de precios en stock: ${valor_total_inventario}")
print(f"Cantidad total de productos: {unidades_totales}")
print(f"El promedio del precio por producto en stock es: ${promedio_precio_stock:.2f}")

El promedio de stock disponible es: 26.25
Suma total de precios en stock: $19100
Cantidad total de productos: 105
El promedio del precio por producto en stock es: $181.90

Combinacion de archivos y consultas

In [34]:
# VENTAS- 
# Calculamos el total de unidades vendidas por cada producto
ventas_por_producto = dat_csv.groupby('producto')['cantidad'].sum().reset_index()

print(f"El total de unidades vendidas por producto es:\n{ventas_por_producto}")

El total de unidades vendidas por producto es:
   producto  cantidad
0  Auxiliar         4
1   Monitor         3
2     Mouse         8
3  Notebook         5
4   Teclado         5

Comparación entre ventas e inventario para calcular stock

In [ ]:
# Unimos especificando qué columna usar de cada lado
ventas_inventario = pd.merge(
    ventas_por_producto, 
    dat_excel, 
    left_on='producto',   # El nombre en el archivo de la izquierda (ventas)
    right_on='nombre'     # El nombre en el archivo de la derecha (inventario)
)

# Calculo de cuánto queda (Stock inicial - Cantidad vendida)
ventas_inventario['stock_final'] = ventas_inventario['stock'] - ventas_inventario['cantidad']
resultado = ventas_inventario[['nombre', 'stock', 'cantidad', 'stock_final']]
resultado.columns = ['Producto', 'Stock Inicial', 'Vendidos', 'Stock Restante']

print(resultado)

   Producto  Stock Inicial  Vendidos  Stock Restante
0   Monitor             15         3              12
1     Mouse             50         8              42
2  Notebook             10         5               5
3   Teclado             30         5              25

¿que producto no esta en el inventario?

In [ ]:
# El parámetro indicator=True nos dirá si el dato está en ambas tablas o solo en la de ventas
verificacion = pd.merge(
    dat_csv, 
    dat_excel, 
    left_on='producto', 
    right_on='nombre', 
    how='left', 
    indicator=True
)

# Estos son los que NO se encontraron en el inventario
no_en_inventario = verificacion[verificacion['_merge'] == 'left_only']['producto'].unique()

# 3. Mostramos el resultado
if len(no_en_inventario) > 0:
    print("Los siguientes productos se vendieron pero NO están en el inventario:")
    for p in no_en_inventario:
        print(f"- {p}")
else:
    print("Todos los productos vendidos existen en el inventario.")

Los siguientes productos se vendieron pero NO están en el inventario:
- Auxiliar